### ISSUE TITLE
How to survive in spacecraft

### ISSUE THREAD

**Issue by jayaddison** [gabrielschulhof/purpose-of-life#1]
Hi @gabrielschulhof - this isn't really an issue report for your repository, but a way to communicate without intruding on your email address.

You might enjoy this talk, 'How to survive in spacecraft' from last year's 'Remote Chaos Experience' event: https://media.ccc.de/v/rc3-158638-how_to_survive_in_spacecraft.

**Comment by jayaddison** [comment]
Since there's no particular action required here - it's purely for notification purposes, I think I'll close this.

**Comment by gabrielschulhof** [comment]
@jayaddison Thanks! I should also add a link to "Time Without End" by Freeman Dyson. Unbeknownst to me he's basically not only expressed, but also quantified a lot of the ideas I collected in this repo - several years before I was born 😀

**Comment by jayaddison** [comment]
@gabrielschulhof You're welcome, and thank you!  I'm reading that now :)
